# Generated by Django 2.1 on 2019-08-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(max_length=300)),
                ('github_link', models.CharField(max_length=300)),
                ('twitter_link', models.CharField(max_length=300)),
                ('linkedin_link', models.CharField(max_length=300)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Barbers')),
            ],
        ),
    ]
