# Generated by Django 2.1 on 2019-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('more_details', models.TextField(blank=True)),
            ],
        ),
    ]
