# Generated by Django 2.1 on 2019-08-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linking',
            name='barber',
        ),
        migrations.AddField(
            model_name='barbers',
            name='facebook_link',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='barbers',
            name='github_link',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='barbers',
            name='linkedin_link',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='barbers',
            name='twitter_link',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.DeleteModel(
            name='Linking',
        ),
    ]
